// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCxHNc9aapsIWgr9LFbTF1nLrexfh6B9qo',
    appId: '1:365639672171:web:93c071378dbe6b511b2c2e',
    messagingSenderId: '365639672171',
    projectId: 'exploremorocco-fa9b7',
    authDomain: 'exploremorocco-fa9b7.firebaseapp.com',
    storageBucket: 'exploremorocco-fa9b7.appspot.com',
    measurementId: 'G-991JCK79XX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCqOHbhBe-4GNC8CMO9ZhR5tW5nH9c-kVw',
    appId: '1:365639672171:android:a2db932b07d839c71b2c2e',
    messagingSenderId: '365639672171',
    projectId: 'exploremorocco-fa9b7',
    storageBucket: 'exploremorocco-fa9b7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD0GoI3Vcdrbs4WbC_Jvhm8g4pUUDvgEAg',
    appId: '1:365639672171:ios:c92844c6075592871b2c2e',
    messagingSenderId: '365639672171',
    projectId: 'exploremorocco-fa9b7',
    storageBucket: 'exploremorocco-fa9b7.appspot.com',
    iosBundleId: 'com.example.exploreMorocco',
  );
}
